### ISSUE TITLE
None of the functions work in Hassbian

### ISSUE THREAD

**Issue by bcrittenden** [wardcraigj/total-connect-client#4] opened 2017-07-30 05:21 UTC
I have been waiting for this functionality for a while. I have this set up and my Hassbian shows the status of my alarm panel but none of the functions work. I have tried them both from the console and as automations and I get nothing. Is there something I am missing?

**Comment by wardcraigj** [comment] 2017-08-10 16:33
Sorry, I intend on looking at this, unfortunately, I'm not living at my place right now as we are undergoing a major renovation. Next time I've got downtime while I'm at the house, I'll look into this

**Comment by wardcraigj** [comment] 2017-08-10 16:35
@schmittx are you able to reproduce this?

**Comment by schmittx** [comment] 2017-08-10 16:57
@bcrittenden What functions are you referring to? Home Assistant currently only supports arm away, arm home, and disarm. If you want to use other arming modes (stay instant, away instant, or stay night) you'd have to create new services within Home Assistant.

FYI, I'm in the process of adding a new service to Home Assistant for arm stay night ([here](https://github.com/home-assistant/home-assistant/pull/8614)).

**Comment by tglicker** [comment] 2017-08-23 17:57
Hello @wardcraigj and @schmittx ,

I am actually running into a similar issue as @bcrittenden. I have set up this component and it seems as if things are set up correctly, but when I try and configure the system to arm away or arm home, it shows that a trigger/signal is sent, but nothing happens on the security system side of things or my totalconnect app which shows the current status. One thing that I have seen on some of the other alarm control panel component is the option of adding a code for one of the configuration variables. Is this not needed for the totalconnect side of things? The reason I ask is because when I use the totalconnect app or alarmnet.com (https://rs.alarmnet.com/TotalConnect2/#/). Any help would be great and please let me know if you would like me to include or clarify anything to help describe the problem. 

Thanks

**Comment by schmittx** [comment] 2017-08-23 22:31
@tglicker The optional code config variable in Home Assistant is only used within the Home Assistant frontend and is not passed to TotalConnect. The TotalConnect component is currently working for me, but it is definitely slow to respond at times (~3 minutes between arming in HASS and when my alarm panel shows "armed"). I think it's a concern on TotalConnect server side.

**Comment by tglicker** [comment] 2017-08-24 03:23
@schmittx , after messing around with a few things tonight it seems as though I am able to get the status of the alarm system to work, but not able to change states. Which makes sense since when I login to TotalConnect on my phone it asks for my username and password and takes me to the main UI where the status of the system is, but when I want to change the state (to arm away or arm stay) I have to type in my code in the UI on a pop up numberpad, just like I have to on the physical system.

While in Home Assistant, when I open the TotalConnect pop up, I can click "Arm Away" or "Arm Home" and then click out of the pop up and see the "Service alarm_control_panel/alarm_arm_away called.", but after waiting for over 10 mins, there is no update on the status or the physical system. Do you think there is a way to add the code into the message that is sent to the TotalConnect server which it seems as if my system seems to need? Or have you seen this behavior before?

**Comment by tglicker** [comment] 2017-08-24 03:36
I also went to look at the .log file and found the following error:

2017-08-23 22:04:06 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/core.py", line 1025, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/__init__.py", line 114, in async_alarm_service_handler
    yield from getattr(alarm, method)(code)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/totalconnect.py", line 88, in alarm_arm_home
    self._client.arm_stay()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/total_connect_client/TotalConnectClient.py", line 67, in arm_stay
    self.arm(ARM_TYPE_STAY, location_name)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/total_connect_client/TotalConnectClient.py", line 88, in arm
    deviceId = self.get_security_panel_device_id(location)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/total_connect_client/TotalConnectClient.py", line 102, in get_security_panel_device_id
    raise Exception('No security panel found')
Exception: No security panel found

**Comment by schmittx** [comment] 2017-08-24 10:19
@tglicker Ahhh, you have the alarm setup within TotalConnect to prompt you for a user code every time when changing states. I don't believe this wrapper (and thus HASS) support that function right now. I'd recommend adding a new user to your alarm panel within TotalConnect for the sole purpose of Home Assistant integration. For that new new user, do **not** have TotalConnect prompt for a user code every time. You'll still have to use a password to login, but it won't prompt for a PIN before arming/disarming/etc. Let me know if this resolves everything.

Like I said before, the code that's an optional config variable in HASS is only for HASS and is never passed on to TotalConnect.

All this being said, it'd be cool to support your current situation. Myself or @wardcraigj might be able to investigate this for a future addition.

**Comment by tglicker** [comment] 2017-08-25 03:35
@schmittx Great suggestion and I have tried to implement this, but have not had any success and still receive the same error message in the homeassistant log as posted above. However, I was able to successfully use the totalconnect phone app in this manner without needing to use enter the user code for the changes.

Got any other thoughts or suggestions on this one?

**Comment by schmittx** [comment] 2017-08-25 03:43
@tglicker Hmm, not really sure. In a possible coincidence, I noticed today that HASS was not connecting properly to my TotalConnect panel (i.e. states weren't updating in HASS and any services called in HASS didn't do anything). Restarting HASS temporarily fixed it for a few minutes each time, but then it'd stop responding. I haven't gone through the logs yet so I'm just guessing at this point. Maybe some server-side on TotalConnect is having problems? Or maybe the application ID/version which are hardcoded into the wrapper are outdated now?

@wardcraigj Any thoughts? Have you been experiencing any problems?

**Comment by tglicker** [comment] 2017-08-25 03:52
I can say that I have noticed both the totalconnect phone app and web interfaces have had major overhauls within the last week or so and they could potentially be making changing to the server as well.

**Comment by uchagani** [comment] 2017-11-02 16:36
any updates on this?  I'm having the same issues.

**Comment by wardcraigj** [comment] 2017-11-03 13:21
Hmm, I haven't been able to reproduce this, though my alarm has only been back up and running after my renos this summer for about two weeks. @schmittx are you still experiencing the issue?

**Comment by uchagani** [comment] 2017-11-03 14:50
@wardcraigj I'm getting a slightly different issue but I think i've figured out the problem.  I'll be submitting a PR later today for it.  Essentially the issue resides in not being able to retrieve the ```LocationName```.

@schmittx I was having the same issue as you and realized the problem was that the user account was not getting synced to the panel.  Once I synced up the user the ```No security panel found``` error went away.

**Comment by uchagani** [comment] 2017-11-03 14:55
Actually, let me back up.  I am getting the same problem and it is caused by the ```LocationName``` issue.  I'm fixing it in a bit.  here's my stack trace:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 190, in disarm
    deviceId = self.get_security_panel_device_id(location)
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 102, in get_security_panel_device_id
    raise Exception('No security panel found')
Exception: No security panel found
```

**Comment by uchagani** [comment] 2017-11-03 15:25
Turns out the issue was with the ```DeviceName``` and not the ```LocationName```.  I've created a PR for the fix.

**Comment by wardcraigj** [comment] 2017-11-03 22:19
Thanks @uchagani! Merged in and updated in pypi. PR for homeassistant here: https://github.com/home-assistant/home-assistant/pull/10322

**Closed by wardcraigj** 2017-11-03 22:19 UTC
